log = true
minLogLevel = 0
release = false

[[modules]]
config = "scheduler.toml"
name = "scheduler"

[[modules]]
config = "console.toml"
name = "console"

[[modules]]
config = "log.toml"
name = "log"

[[modules]]
config = "http.toml"
name = "http"

[[modules]]
config = "socks5.toml"
name = "socks5"
