[modules.gate]
paths = ["gate.toml"]
buf = 10

[modules.login]
paths = ["login.toml"]
buf = 10

[modules.match]
paths = ["match.toml"]
buf = 10

[modules.room]
paths = ["room.toml"]
buf = 10

[mysql.JFFun]
user = "vongola"
password = "123"
addr = "localhost:3306"

[redis.JFFun]
db = 0
addr = "localhost:6379"